### ISSUE TITLE
Horde spawn inside of trader POI

### ISSUE THREAD

**Issue by wisathestray** [FilUnderscore/ImprovedHordes#14]
**Describe the bug**
Playing A21 on server with Improved Hordes 2.0.0 had a full horde spawning within a trader POI.

**To Reproduce**
I don't know how I could reliably recreate the bug as the player cannot control specifically where a horde will spawn.  However, the trader gates were all closed so these zombies didn't just wander in - they definitely spawned within the trader POI.  The two players on our server were outside of the POI when the horde spawned, probably 50 - 100 m from the trader's fence.  Desert biome, Trader Hugh in case that's pertinent.

**Expected behavior**
I would expect that the trader POI would be treated as a non-spawnable area and would not allow a horde.

**Additional context**

**Comment by FilUnderscore** [comment]
Thanks for reporting this. Currently working on a fix where hordes should be spawned just outside POIs and will keep you updated.

**Comment by FilUnderscore** [comment]
This should be fixed in the latest release 2.0.0-beta.2. 

This has been fixed as the following (from changelog):
> * POI and Land Claim Block spawn check to prevent horde entities from spawning in POIs and player bases.

Please re-open this issue if you are still encountering it in the latest version. Thanks!
