### ISSUE TITLE
exception occurred during UpdateAsync

### ISSUE THREAD

**Issue by Junrall** [FilUnderscore/ImprovedHordes#16]
I'm not seeing any hoards at all.

I am seeing a continuous stream of the same error in the console:
[Player.log](https://github.com/FilUnderscore/ImprovedHordes/files/12298383/Player.log)

**Comment by FilUnderscore** [comment]
Thanks for reporting this. It seems to be related to a horde type being unable to be spawned.

Have you by any chance removed one of the `<horde type="">` entries in the hordes.xml file? That would be the most likely cause of this error just from looking at the log so far.

Any additional information would be helpful in figuring out what could be causing this error to happen, and how it can be fixed to prevent this issue from happening in the future.

**Comment by Junrall** [comment]
Umm.....
I took a look at the hordes.xml. It looks as if I had removed the screamers section... I hadn't taken the mental leap that your dll file accesses this! I'm so sorry for the false report.
Is there a way to safely remove screamers? I tried a separate mod for this but it seems to be overridden by Improved Hordes?

**Comment by FilUnderscore** [comment]
> Umm..... I took a look at the hordes.xml. It looks as if I had removed the screamers section... I hadn't taken the mental leap that your dll file accesses this! I'm so sorry for the false report. Is there a way to safely remove screamers? I tried a separate mod for this but it seems to be overridden by Improved Hordes?

Improved Hordes disables the vanilla screamers and replaces it with screamer spawns only in towns. If you want to get rid of screamers completely, you could replace the `zombieScreamer` entity in the config with a `animalRabbit` or `animalChicken`.

I'm currently revising the approach to screamers and horde configuration (removing/disabling hordes) which will be included in the next update. There currently isn't an implementation that ignores if a horde entry isn't present in the config just yet, sorry about that.

**Comment by Junrall** [comment]
Thank you! Haha, now I'll always be wondering if that chicken is REALY a chicken.
