### ISSUE TITLE
Commands for testing

### ISSUE THREAD

**Issue by YakovAU** [FilUnderscore/ImprovedHordes#28]
Is there a command or function i can invoke to 'trigger' a horde with the parameters ive set in the settings.xml (to ensure its working)
Similar to the vanilla spawnwh command?

**Comment by FilUnderscore** [comment]
> Is there a command or function i can invoke to 'trigger' a horde with the parameters ive set in the settings.xml (to ensure its working) Similar to the vanilla spawnwh command?

Most of the settings refer to populating hordes across the world, so there would be no easy way to test this with a command but you can teleport around and encounter some hordes in the game. Horde settings have mainly been confined to the hordes.xml.

There is a debug client that I use to look at horde populations that is provided in the source code - I'm looking to include a build of it as an optional download, but you can currently compile it yourself using the latest JDK. The source is provided under `Source/IHDebugViewer` as a maven project. 

To use the debug client, you'll need to compile a Debug build of ImprovedHordes which enables the debug commands, allowing you to run `improvedhordes debug server` which starts up the mod debug server. You then need to start the debug client and hit "Connect" and it will connect to the debug server, displaying all info regarding hordes in the world. The debug client currently only supports localhost.
