### ISSUE TITLE
Could you add an option to remove the mod announcement on a player join?

### ISSUE THREAD

**Issue by BoQsc** [FilUnderscore/ImprovedHordes#32]
**Describe the bug**
When you join a server you are met with announcement of Improved Hordes and its version.  
It can be annoying for a simple minimalistic server.

**To Reproduce**
1. Activate ImprovedHordes `.dll` modlet inside your server by dropping in the `mods` folder
2. Start the game server.
3. Wait for the game server to load.
4. Join the game server as a player.
5. Look at Improved Hordes message that welcomes you.

**Expected behavior**
No messages should appear when a player joins the game server.

**Screenshots**
![image](https://github.com/FilUnderscore/ImprovedHordes/assets/21064622/d1b42ba7-eb59-42cf-b64c-85561527264f)

**Comment by FilUnderscore** [comment]
This feature has been implemented already due to a previous request - in the settings.xml file, there is a setting `silence_init_msg` which you can set to true to prevent this message from popping up on login.

**Comment by BoQsc** [comment]
Thanks, it worked. `Config\ImprovedHordes\settings.xml `
![image](https://github.com/FilUnderscore/ImprovedHordes/assets/21064622/a9cdb8fb-0c51-4d2c-81e5-206c9931ac08)
