### ISSUE TITLE
1.0 possibly?

### ISSUE THREAD

**Issue by YakovAU** [FilUnderscore/ImprovedHordes#33]
I love IH, hope its coming to 1.0.

**Comment by FilUnderscore** [comment]
Working on #34 which will make IH fully compatible with 1.0, expecting to release an experimental build soon.

**Comment by FilUnderscore** [comment]
Released an experimental build that should be compatible with 1.0 experimental, 2.0.1-RC.1.

**Comment by YakovAU** [comment]
awesome work
