### ISSUE TITLE
Improved Logs 

### ISSUE THREAD

**Issue by 200779b** [FilUnderscore/ImprovedHordes#6]
I don't really think this is related to Improved Hordes, but I really think 7D2D community would benefit from a new mod that enhances what gets logged.
For starter, I'm thinking when a player uses an item, his name, the item used, and the coords of where it was used show up in the logs. Not any item, but those indicated in the list file (xml or not). That would open so many possibilities...
Combined with csmm server manager, a custom food/book could teleport the player, spawn zombies/horde, send private/public messages, reset the char, affect players close, add "virtual" currency and much more.

**Comment by trevorjd** [comment]
Disclaimer: I'm not a programmer and I haven't modded for 7D.

Based on what I know from Ark & Atlas, each item is an Object and has its own set of functions. I expect it's possible to create a custom object that writes a log entry on use (e.g. on a left click, right click, placement, or in-inventory like repairing a weapon). However, I expect that would require a client-side mod.

To do it fully server side, you'd need something that is constantly looking through events coming from clients (which I expect would look like gun_fired, bandage_applied or activate_hotbar_slot_3) and then iterating through the list of triggers, and then making its log entries for CSMM to detect. I worry that this level of deep inspection would be difficult to do and extremely heavy on server performance.

While it might be more immersive to activate a handheld remote in-game to teleport you, it certain is a lot easier to use existing waypoint functionality with /settele <name> and /tele <name>. 

Botman (CSMM's competitor) had a /hordeme command. I think that would be pretty simple to implement with CSMM.

I didn't set it up myself but our server runs something that adds a virtual currency. Players can vote and get coins which they can spend at the /shop and use to fund use of the /tele command.

**Comment by 200779b** [comment]
Csmm/cpm have a targeted horde command. 
It's one thing to let the players choose when to do it (which has a fixed amount of zombies) and another thing to surprise them or set if/then conditions to determine which or how many zombies will spawn. 
The process of deposit dukes and make them become the virtual currency (which we already use) would be much easier if players could just read a custom item (like a deposit certificate), instead of relying on a secure chest to do it.
Players can teleport themselves, but can they teleport themselves and everyone in a ten blocks radius? 
There is a lot the just can't be acomplished because we can't stablish who did what and where.

**Comment by FilUnderscore** [comment]
> I don't really think this is related to Improved Hordes, but I really think 7D2D community would benefit from a new mod that enhances what gets logged. Combined with csmm server manager, a custom food/book could teleport the player, spawn zombies/horde, send private/public messages, reset the char, affect players close, add "virtual" currency and much more.

Really not related and seems like a whole mod request that would need to be more fleshed out in terms of what functionality to offer. This seems more like a feature that would be better added for CPM instead of a separate mod. Have you tried requesting this functionality over at the CSMM/CPM discord?

> It's one thing to let the players choose when to do it (which has a fixed amount of zombies) and another thing to surprise them or set if/then conditions to determine which or how many zombies will spawn.

There is no such functionality within the mod at this time that will allow you to do this, and the horde types are currently hardcoded to wandering and scout for the time being.
