### ISSUE TITLE
Mod compatibility check - Avoid Bloodmoon Injection

### ISSUE THREAD

**Issue by trevorjd** [FilUnderscore/ImprovedHordes#7]
Hi Fil,

I was wondering if you could say one way or the other if the mod Avoid Bloodmoon Injection is likely to have any conflicts with Improved Hordes.

https://7daystodiemods.com/avoid-bloodmoon-injection-sp-mp-dedicated/

Cheers,
Trev

**Comment by FilUnderscore** [comment]
Shouldn't have any conflicts with the mod since it deals with code specific to the blood moon horde.

**Comment by trevorjd** [comment]
Thanks very much!
